### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by LYZ1125** [xtt5480446/GUIDER#2]
Hi, when I run this command at the root:
```
Main/Main -a 'google driver 1' -c 'google driver 1' -r /Users/nju/Documents/issta-artifact/ -o /Users/nju/Desktop/apk/app-fdroid-debug-old.apk -n /Users/nju/Desktop/apk/app-fdroid-debug-new.apk -v 7.0 -w 10 -p 'com.google.android.apps.docs' -t 'com.google.android.apps.docs.app.NewMainProxyActivity' -l guider
```
But it can not run.
It just need to run this command at `C:\Users\Desktop\work\Guider\Main>`?
What kind of file is Main? What to use to run it. My computer displays:'Main' is not an internal or external command, nor is it an executable program or batch file.

**Comment by metter2018** [comment]
> Hi, when I run this command at the root:
> 
> ```
> Main/Main -a 'google driver 1' -c 'google driver 1' -r /Users/nju/Documents/issta-artifact/ -o /Users/nju/Desktop/apk/app-fdroid-debug-old.apk -n /Users/nju/Desktop/apk/app-fdroid-debug-new.apk -v 7.0 -w 10 -p 'com.google.android.apps.docs' -t 'com.google.android.apps.docs.app.NewMainProxyActivity' -l guider
> ```
> 
> But it can not run.
> It just need to run this command at `C:\Users\Desktop\work\Guider\Main>`?
> What kind of file is Main? What to use to run it. My computer displays:'Main' is not an internal or external command, nor is it an executable program or batch file.

Hi, GUIDER executable file is made for Mac OS at present, and we will release the Windows version GUIDER later.  
Besides, before executing Main/Main, android SDK and Appium is required (you can follow the related links in this git )
Before

**Comment by LYZ1125** [comment]
Thanks
